Traceback (most recent call last):
  File "/home/alexandrasouverneva/Desktop/my-book-files/venv/lib64/python3.9/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexandrasouverneva/Desktop/my-book-files/venv/lib64/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/alexandrasouverneva/Desktop/my-book-files/venv/lib64/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/alexandrasouverneva/Desktop/my-book-files/venv/lib64/python3.9/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/alexandrasouverneva/Desktop/my-book-files/venv/lib64/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/alexandrasouverneva/Desktop/my-book-files/venv/lib64/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/alexandrasouverneva/Desktop/my-book-files/venv/lib64/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from rdkit import Chem

unique_smiles_freq = dict()

suppl = Chem.SDMolSupplier('cid2sids-uracil.sdf')

for mol in suppl:

    smiles = Chem.MolToSmiles(mol,isomericSmiles=True)

    unique_smiles_freq[ smiles ] = unique_smiles_freq.get(smiles,0) + 1

sorted_by_freq = [ (v, k) for k, v in unique_smiles_freq.items() ]
sorted_by_freq.sort(reverse=True)
for v, k in sorted_by_freq :
    print(v, k)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mrdkit[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Chem
[1;32m      3[0m unique_smiles_freq [38;5;241m=[39m [38;5;28mdict[39m()
[1;32m      5[0m suppl [38;5;241m=[39m Chem[38;5;241m.[39mSDMolSupplier([38;5;124m'[39m[38;5;124mcid2sids-uracil.sdf[39m[38;5;124m'[39m)

[0;31mModuleNotFoundError[0m: No module named 'rdkit'

